// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr1G1ofOS1ljLLn_5CDS7L85jGy99EvAY',
    appId: '1:848035100060:web:61b0560257ae09381b4459',
    messagingSenderId: '848035100060',
    projectId: 'bunnypages-ce5a4',
    authDomain: 'bunnypages-ce5a4.firebaseapp.com',
    storageBucket: 'bunnypages-ce5a4.firebasestorage.app',
    measurementId: 'G-NHSXJMC9WB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-ESX63ZQZ9ykzlZS5ZLVSUl1K75ZWPcg',
    appId: '1:848035100060:android:9914bc72aa21a2841b4459',
    messagingSenderId: '848035100060',
    projectId: 'bunnypages-ce5a4',
    storageBucket: 'bunnypages-ce5a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRnfu06mA_JHRAo3oWE2t00NaEFeOIf5s',
    appId: '1:848035100060:ios:d0a98a80405b6ab31b4459',
    messagingSenderId: '848035100060',
    projectId: 'bunnypages-ce5a4',
    storageBucket: 'bunnypages-ce5a4.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRnfu06mA_JHRAo3oWE2t00NaEFeOIf5s',
    appId: '1:848035100060:ios:d0a98a80405b6ab31b4459',
    messagingSenderId: '848035100060',
    projectId: 'bunnypages-ce5a4',
    storageBucket: 'bunnypages-ce5a4.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr1G1ofOS1ljLLn_5CDS7L85jGy99EvAY',
    appId: '1:848035100060:web:3dbe6ea41b89f4881b4459',
    messagingSenderId: '848035100060',
    projectId: 'bunnypages-ce5a4',
    authDomain: 'bunnypages-ce5a4.firebaseapp.com',
    storageBucket: 'bunnypages-ce5a4.firebasestorage.app',
    measurementId: 'G-DP98SHJ167',
  );
}
